name: code_snippets
description: Experimental builder for dealing with code snippets.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  analyzer: ^3.2.0
  build: ^2.2.1
  collection: ^1.15.0
  meta: ^1.7.0
  source_span: ^1.8.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.12.1
