name: docsy
description: Port of docsy to built_site
version: 0.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bootstrap_sass: ^4.5.0
  built_site:
    hosted:
      url: https://simonbinder.eu
      name: built_site
    version: ^0.2.0
  build_config: ^1.0.0

dependency_overrides:
  built_site:
    path: ../../built_site
