name: jaspr_docsy
description: A port of the Docsy documentation theme to jaspr_content.
version: 0.0.5

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.0
  jaspr_content: ^0.4.5
  universal_web: ^1.1.1

  bootstrap:
    hosted: https://pub-simonbinder-eu.fsn1.your-objectstorage.com
    version: ^5.3.8
